@startuml

class 口座 {
    番号
    名称
    is出荷可能(希望数量, 希望日) : boolean
}

class 入荷見込み
class 出荷見込み
class 入荷履歴
class 出荷履歴

class 入荷予定 {
    日付
    数量
}

class 出荷予定 {
    日付
    数量
}

class 入荷実績 {
    日付
    数量
}

class 出荷実績 {
    日付
    数量
}

口座 --> 入荷見込み
入荷見込み  *-- "*" 入荷予定

口座 --> 出荷見込み
出荷見込み  *-- "*" 出荷予定

口座 --> 入荷履歴
入荷履歴  *-- "*" 入荷実績

口座 --> 出荷履歴
出荷履歴  *-- "*" 出荷実績

@enduml