@startuml

顧客 --> 販売部門 : 注文する
販売部門 --> 販売部門 : 在庫を確認する
販売部門 --> 出荷部門 : 出荷を指示する
出荷部門 --> 顧客 : 出荷する
出荷部門 --> 経理部門 : 出荷を報告する
顧客 --> 顧客 : 商品を受け取る
経理部門 --> 顧客 : 請求する
顧客 --> 経理部門 : 支払う
経理部門 --> 経理部門 : 入金を確認する

@enduml