@startuml

class 注文 {
    注文番号
    注文金額() : 金額
}

class 注文明細 {
    List<明細行>
    合計() : 金額
}

class 明細行 {
    数量
    単価
    金額() : 金額
}

class 数量 {
    int Value() : int
}

class 金額 {
    multiply(数量) : 金額
}

class 顧客 {
    名称
}

class 商品 {
    単価
}

注文 --> 注文明細
顧客 <- 注文
注文明細 --> 明細行
商品 <- 明細行
明細行 --> 数量
明細行 --> 金額

@enduml